### ISSUE TITLE
Should this project have adapters / appenders or behave like a Log4j for javascript?

### ISSUE THREAD

**Issue by pdorgambide** [pdorgambide/angular-logger#20]
Change log levels at run time on console. Maybe it is already or near posible since the right  LogginEnhancer separation. I think that  the global LoggingEnhancer variable could do the trick.
If so we would inform at readme of this awesome issue.

**Comment by bbottema** [comment]
This is very much possible (and is planned). the jasmine unit test included actually already does this with a simple dummy object which has some empty methods.

In fact I propose to rename this repo to "better-logging.js" in some time and instead of focusing on just angular's $log, provide adapters for window.console _and_ $log _and_ other popular logging frameworks. As the integration is really rather simple (we replace arguments that go into the original logging function), these should be trivial tasks.

I want to perfect _logging-enhancer.js_ just a bit more and then we can start replace the Readme.md with a proper wiki and on the Readme only explain the concept of logging enhancement and show adapter examples.

What do you think? I thought of having a different repo per adapter, but then you end up having 6 repo's all with a single .js source file. A bit heavy for what they do, me thinks.

**Comment by pdorgambide** [comment]
I am agree with you. 
The main goal of the library, when I decided to create it, was take log4j API that exists for Java and traslate it to the JS enviroments (browser).
I know that already exists [log4js-node](https://github.com/nomiddlename/log4js-node) but I think that it is focused on node.js, I don't know if it can run on browser. 

To organize the repositories I think we may continue the name convention and one option could be log4js-base, log4js-console,log4js-angular,log4js-otheradapter.
- log4js-base: For base libraries and tools. I think that it couldn't be necesary if consider the console as the base layer for the adapters.
- log4js-console:  Would be use native console methods and could be the base layer for other adapters (at less for the $log, could be used)
- log4js-angular: For use log4js with angular. The integration can be done by replace the default $log service with the log4js-angular at with the help of [$delegate and $provider.decorator](http://blog.xebia.com/2014/08/08/extending-angularjs-services-with-the-decorate-method/)
  Future issues would include some of the log4j api issues: Adapters, and so on.

I will try help you in I could, but the next months I don't have enough time as my second son just born and I need to configure other libraries.. ;oP.
You are doing a great work, I think that you technical skills in JS are bigger than the mine. Congratulations.

**Comment by bbottema** [comment]
A couple of things:
1. Actually, since 2014 there is a conversion project for that [converts log4js-node to log4js](https://github.com/stritti/log4js). It seems to be missing a lot but has support for more frameworks through appenders. Documentation is severely lacking and the source is a lot more complex.  The project seems to have become inactive as well.
2. I think we're in a good position to provide a more robust log4js. At least in spirit of log4js, because I prefer convention of configuration (sensible defaults) and maximum ease of use with least amount of code.
3. There is a fundamental difference in approach, however: log4j(s) would provide a factory to produce loggers and use appenders to relay the output to various channels (file, console, $log, REST). However, currently angular-logger works by _enhancing_ existing logging methods. That is: enhanced `$log.debug()` vs `Log4js.getLogger(new AngularLogAppender($log))`. With the first approach it works as a transparent drop-in, code can stay the same and produce better logging. In the second approach it cannot be dropped in as a replacement and all the logging statements need to be rewritten. Which approach do we want?

What we need now is to think of a bunch of code examples that illustrate the API that we want.

**Comment by bbottema** [comment]
At any rate, I made a new organisation and repo both named log4js so it is not tied to one specific person. I added us both as repo maintainers and I made an initial copy of this repo.

Let's figure out what we want to do now. I still like the idea of having drop-ins for `console.debug` and `$log.warn`. We can do both too, using a common base for both. The base module can handle generating a prefix and mixing in sprintf support while angular-logger uses that base to enhance $log and log4js uses that base and adds appenders to it for channeling the output.

So now I'm thinking of something along the lines of the following:

``` javascript
'[logging-enhancer]'
        \--- '[better-angular-logging]' // stand-alone drop-in, in own repository
        \--- '[better-console-logging]' // stand-alone drop-in, in own repository
        \--- '[better-some-logging-library]' // stand-alone drop-in, in own repository
        \--- '[log4js]' // in own repository
                \--- '[angular-appender]' // in log4js repository
                \--- '[console-appender]' // in log4js repository
                \--- '[some-logging-library-appender]' // in log4js repository
                \--- '[ajax-appender]' // for REST version, in log4js repository
                \--- '[file-appender]' // for node version, in log4js repository
```

It's actually easier to go from a browser version to a node version. I think you can actually use the same code unchanged. Only the _file-appender_ would fail to load in a browser.

**Comment by pdorgambide** [comment]
As you say I think that in terms of a log library the right challenge will be do it as **less invasive as posible** because this allow not change the existing code, programmers conventions, ....

At _angular context_ ( I am an angular geek, have you noticed? ) one ideal way will be take a automatic context configuration (for  the $log service) based on the invocation context (_module + [controller,directive,service]_). If we could take a form that allow to _$log_ know the context we could enable/disable the debug without any invasive code (without use _$log.getInstance("Context")_ and from the config phase we can configure adapters/level etc with pattern like _moduleName.controllerName_ (I am sorry if my explanation, as my english, is not very clear ;o( )

For other context (_backbone, jquery_,... I am not a geek) we need to get any similar form. 

From your proposal layout, I will remove the _better-_  prefix as we suppose that our library is the better, do you not?) and _logger_ sufix  insted of _logging_ sounds me better (but I am not an expert take it with care).

You are in the right way and make a great work.

**Comment by bbottema** [comment]
Good point regarding automatic context derivation. We'll have to find out how to get those, though.

Regarding proposal layout: I started moving everything under two organisations: [better-logging](https://github.com/better-js-logging) and [log4js](https://github.com/log4js). Better logging will contain the base for enhanced logging and the framework specific logging adapters, log4js will contain, well, the new log4js framework (which also refers to the better logging base). I can rename better-logging-angular as angular-logger, though it still doesn't sound quite right. It doesn't help that we are both non-native english speakers either :)

I already [moved the base](https://github.com/better-js-logging/better-logging-base) and switched to [browserify](http://browserify.org/) so that it can easily be used in other libraries without polluting the `window` global.

All names are up for change, I haven't released anything yet.

**Comment by pdorgambide** [comment]
I think that it will be hard to solve... I post it  at stackoverflow.
[get-module-and-controllerservicedirective-names-at-runtime](http://stackoverflow.com/questions/30556328/get-module-and-controllerservicedirective-names-at-runtime)

**Comment by bbottema** [comment]
I think this repo can be closed soon. I made a first working version of the [console-logger](https://github.com/better-js-logging/console-logger) under the new organization as well. I'm going to release both logger libraries soon over there. Once _console-logger_ works properly and has some test-coverage, I'll begin working on _log4js_.

**Comment by bbottema** [comment]
I released the first version of console-logger and updated the docs and working demo.

https://github.com/better-js-logging/console-logger

**Comment by bbottema** [comment]
I now also registers it as a bower package with the name "angular-logger". We'll move this dicussion over to https://github.com/better-js-logging/angular-logger/issues/3
